namespace: kube-state-metrics
resources:
  - namespace.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - deployment.yaml
  - networkpolicy.yaml
  - prometheusrule.yaml
  - service.yaml
  - serviceaccount.yaml
  # Disable servicemonitor now so that the selfmetrics collector can scrape this pod explicitly
  # and the core-prometheus collector doesnt also scrape it.
  # - servicemonitor.yaml
