namespace: prometheus
resources:
  - namespace.yaml
  - kubePrometheus-prometheusRule.yaml
  - kubernetesControlPlane-prometheusRule.yaml
  - prometheus-clusterRole.yaml
  - prometheus-clusterRoleBinding.yaml
  - prometheus-networkPolicy.yaml
  - prometheus-podDisruptionBudget.yaml
  - prometheus.yaml
  - prometheusrule.yaml
  - prometheus-roleBindingConfig.yaml
  - prometheus-roleBindingSpecificNamespaces.yaml
  - prometheus-roleConfig.yaml
  - prometheus-roleSpecificNamespaces.yaml
  - prometheus-service.yaml
  - prometheus-serviceAccount.yaml
  - virtualservice.yaml
  - authorizationpolicy.yaml
  - grafanadatasource.yaml
  - grafanafolder.yaml
  - grafanadashboard.yaml
  - thanos-sidecar-service.yaml
  - servicemonitor.yaml

generators:
  - sopsgenerator.yaml
