apiVersion: v1
kind: Secret
metadata:
    name: thanos-objectstore
type: Opaque
stringData:
    thanos.yaml: ENC[AES256_GCM,data:y6gjmMreazZQwmwDQD4+dy4135k9OPlu/PcW+R4LxkGPAtHpuR4xfJINHbSeFYJfpXKKQxVNlsTeHQhPYvBOnOH1Ri3+Qh2RnQAk2ziUCfsShyELnxU2Cz5sGnh2Ld6d4qbp5Ti4RGV7T9kHf7HwdHSsC1oteg5SSQmVXnBnVDsvTbDyxFhTuJtFtKYvpEyhwlOaFfRI+YPyituOFs2valk8K6yW2uXI6V3jHQTDaszMaDS98PRGTF/ETaLZDq1UY01SDxDyglfyAsAQly7N9LPkbYtkRuhCqzwA28jZv5uDyo4zmln+wY/zaOYtxNgsWegcuNwfLPncjlH9aMTbpPv7HxRaMbhzTBPh9Wa+U3VCFQESaMBZGser6wXytyd/wvujtwIOAC/+zc/tGd+2Ot+/VOI=,iv:WZmCY4ay5OS2gJf3dZXXjX/lBC5+J302vGKpUaFqxN8=,tag:eRZxU6ws7i+oKi1inzdmIg==,type:str]
sops:
    age:
        - recipient: age15x8mqr8j40rtzeg98wa536jt85276crszk7qcrprndveq4049esq6padka
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTUFUyZlBKRkZ5OUR1SWpp
            dU4xMGdSTENzT05FY05FcTdHRXhKQXdDOGxnCng3STdTRytqejBCNzd1Qml0dFFV
            VVAxWW94NEV2djVIYmN4R1RTZktsQjQKLS0tIFdyK2cvejlKZjFVdms1cWl1RW1v
            Vk94UExXaGNqUU1aU3dZbXpLd0hKcUkKEyEPibSbdcw8n2NfeYAchC5ZZykcoRlL
            6RXIRwEjcCG5HLMtLyQAO/Jh2i6RheKQ6rSDOlsxMMIUhx7omf2H9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-18T00:36:53Z"
    mac: ENC[AES256_GCM,data:TAUmvjMURPAYhmnQ54oicp34mwVqS2vza9n2J0+kDU6w9OYmqXCmYzwK5SJ1HJZeUeLnEZKKd0ZN84xAYMI+5UJOPgsroOd+CaA+ma1NhZArCSdJFEJs2p8H7ArJM+4+Cu9gMV/Vup0IjDX0zZmE6FtFvZHmzVB94Cvm5wTKXZY=,iv:8xJEiFAOOQtQoWirvdTl5vmazP945B1Mmh7rBi7+vNM=,tag:0R4EjoP752RjmsQIuncnxQ==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: thanossidecar-tracing-config
type: Opaque
stringData:
    tracing.yaml: ENC[AES256_GCM,data:RRG1ZsqRkB6wKx8e8kTCS3Y5HspZKwrNJjnNZFPBN7iAxcy4aLgmUucQD2HH0cXX8YThBicMNA2OKDxlnD0DCCVwEXskMHkiiDLRmtJyn1wQLCBMgImUwdM1RkJCyAADyzlX7aL300jSQllBNq0hCqF7+NtFw+y92qjz2F6p3ahuf39BgjSwlTnVTaWQyVuw1q9tF3EhJcCtACHXJ2+g0wGaZRNjyjKiP2Zy5Cvm2WkmMalYoGdtuYKEI9DOQ2tuLgpccB55gXdNy1Q1gndV588vdsGUX8HAhXnPhSUP47cU5q8eCMTs3L8Xm+QdldeO5LRDcy3PfsTZelJAK2QjzJxFviBQpzpOLdCkmtIMTa+nVPC2l8angiUUbmE8O4HzZMwwwsBI/+l8nJ4XelEFWKxlycW3AkFkWDUtugVaNa1q3RXAfTSV34co9a4PydCGGt40j6n76lStTSYp1NvpklcEbHSMSNxM7/vu1UU7NNU=,iv:O4Hx344lC5fbL2N2pvlrFKLyzh7rfZ84JlLhOycnXjM=,tag:GNOKrCQNkZjqNLLCoJrOcw==,type:str]
sops:
    age:
        - recipient: age15x8mqr8j40rtzeg98wa536jt85276crszk7qcrprndveq4049esq6padka
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTUFUyZlBKRkZ5OUR1SWpp
            dU4xMGdSTENzT05FY05FcTdHRXhKQXdDOGxnCng3STdTRytqejBCNzd1Qml0dFFV
            VVAxWW94NEV2djVIYmN4R1RTZktsQjQKLS0tIFdyK2cvejlKZjFVdms1cWl1RW1v
            Vk94UExXaGNqUU1aU3dZbXpLd0hKcUkKEyEPibSbdcw8n2NfeYAchC5ZZykcoRlL
            6RXIRwEjcCG5HLMtLyQAO/Jh2i6RheKQ6rSDOlsxMMIUhx7omf2H9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-18T00:36:53Z"
    mac: ENC[AES256_GCM,data:TAUmvjMURPAYhmnQ54oicp34mwVqS2vza9n2J0+kDU6w9OYmqXCmYzwK5SJ1HJZeUeLnEZKKd0ZN84xAYMI+5UJOPgsroOd+CaA+ma1NhZArCSdJFEJs2p8H7ArJM+4+Cu9gMV/Vup0IjDX0zZmE6FtFvZHmzVB94Cvm5wTKXZY=,iv:8xJEiFAOOQtQoWirvdTl5vmazP945B1Mmh7rBi7+vNM=,tag:0R4EjoP752RjmsQIuncnxQ==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
