# TODO maybe set namespace to be cilium instead of kube-system via the helm template:
# helm template \
#    cilium \
#    cilium/cilium \
#    --version 1.18.0 \
#    --namespace kube-system \
#    --set ipam.mode=kubernetes \
#    --set kubeProxyReplacement=true \
#    --set securityContext.capabilities.ciliumAgent="{CHOWN,KILL,NET_ADMIN,NET_RAW,IPC_LOCK,SYS_ADMIN,SYS_RESOURCE,DAC_OVERRIDE,FOWNER,SETGID,SETUID}" \
#    --set securityContext.capabilities.cleanCiliumState="{NET_ADMIN,SYS_ADMIN,SYS_RESOURCE}" \
#    --set cgroup.autoMount.enabled=false \
#    --set cgroup.hostRoot=/sys/fs/cgroup \
#    --set cni.exclusive=false \
#    --set k8sServiceHost=localhost \
#    --set k8sServicePort=7445 \
#    --set gatewayAPI.enabled=true \
#    --set prometheus.enabled=true \
#    --set operator.prometheus.enabled=true \
#    --set hubble.enabled=true \
#    --set hubble.metrics.enableOpenMetrics=true \
#    --set hubble.metrics.enabled="{dns,drop,tcp,flow,port-distribution,icmp,httpV2:exemplars=true;labelsContext=source_ip\,source_namespace\,source_workload\,destination_ip\,destination_namespace\,destination_workload\,traffic_direction}" \
#    --set gatewayAPI.enableAlpn=true \
#    --set gatewayAPI.enableAppProtocol=true >! cilium.yaml

resources:
  - cilium.yaml
  - namespace.yaml
  - grafanafolder.yaml
  # Disabling hubble for now
  # - httproute.yaml
  - networking.yaml
  # Disabling due to the annotation length being too big, can probably re-enable and just remember to always do the --server-side force conflicts things when running k apply -k .
  # - grafanadashboard.yaml
