apiVersion: v1
kind: Service
metadata:
  name: tempo-querier
  labels:
    helm.sh/chart: tempo-distributed-1.52.9
    app.kubernetes.io/name: tempo
    app.kubernetes.io/instance: tempo
    app.kubernetes.io/component: querier
    app.kubernetes.io/version: "2.9.0"
    app.kubernetes.io/managed-by: Helm
spec:
  ipFamilies: [IPv4]
  ipFamilyPolicy: SingleStack
  ports:
    - name: http-metrics
      port: 3200
      protocol: TCP
      targetPort: http-metrics
    - name: grpc
      port: 9095
      protocol: TCP
      targetPort: 9095
  selector:
    app.kubernetes.io/name: tempo
    app.kubernetes.io/instance: tempo
    app.kubernetes.io/component: querier
