apiVersion: v1
kind: Service
metadata:
  name: thanos-memcached-index
  labels:
    app.kubernetes.io/name: thanos-memcached-index
    app.kubernetes.io/component: cache
spec:
  ports:
  - name: client
    port: 11211
    targetPort: 11211
  selector:
    app.kubernetes.io/name: thanos-memcached-index
  clusterIP: None # Headless service for Memcached discovery
