namespace: jellyfin
resources:
  - namespace.yaml
  - deployment.yaml
  - statefulset.yaml
  - service.yaml
  - virtualservice.yaml
  - authorizationpolicy.yaml
  - servicemonitor.yaml
  - grafanafolder.yaml
  - grafanadashboard.yaml
  - probe.yaml
generators:
  - sopsgenerator.yaml
