namespace: cockpit
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - virtualservice.yaml
  - authorizationpolicy.yaml
  - configmap.yaml
  - probe.yaml
generators:
  - sopsgenerator.yaml
