namespace: pyroscope
resources:
  - namespace.yaml
  - service.yaml
  - deployment.yaml
  - servicemonitor.yaml
  - virtualservice.yaml
  - authorizationpolicy.yaml
  # - python-fast-slow.yaml
  - grafanadatasource.yaml
  - telemetry.yaml
  - probe.yaml

configMapGenerator:
- files:
  - files/pyroscope.yaml
  name: config
  options:
    immutable: true
