apiVersion: v1
kind: Service
metadata:
  name: kube-proxy
  labels:
    app: kube-proxy
    jobLabel: kube-proxy
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/version: "79.7.1"
    app.kubernetes.io/part-of: kube-prometheus-stack
    chart: kube-prometheus-stack-79.7.1
    release: "prometheus"
    heritage: "Helm"
spec:
  clusterIP: None
  ports:
    - name: http-metrics
      port: 10249
      protocol: TCP
      targetPort: 10249
  selector:
    k8s-app: kube-proxy
  type: ClusterIP
