namespace: thanos
resources:
  - thanosruler.yaml
  - servicemonitor.yaml
  # - authorizationpolicy.yaml
  # - virtualservice.yaml
  - grafanadashboard.yaml
  - prometheusrule.yaml
  # - telemetry.yaml

generators:
  - sopsgenerator.yaml
