namespace: thanos
resources:
  - thanosruler.yaml
  - servicemonitor.yaml
  - grafanadashboard.yaml
  - prometheusrule.yaml
  - httproute.yaml
  # - telemetry.yaml

generators:
  - sopsgenerator.yaml
