namespace: opencost
resources:
  - namespace.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - service.yaml
  - serviceaccount.yaml
  - deployment.yaml
  - virtualservice.yaml
  - servicemonitor.yaml
  - authorizationpolicy.yaml
  - grafanafolder.yaml
  - grafanadashboard.yaml
  - probe.yaml

configMapGenerator:
  - files:
    - files/default.json
    name: custom-pricing-model
    options:
      immutable: true
