namespace: thanos
resources:
  - redis.yaml
  - deployment.yaml
  - servicemonitor.yaml
  - serviceaccount.yaml
  - service.yaml
  - virtualservice.yaml
  - authorizationpolicy.yaml
  - grafanadashboard.yaml
  - telemetry.yaml
