namespace: authelia
resources:
  - namespace.yaml
  - postgres
  - redis
  - deployment.yaml
  - service.yaml
  - virtualservice.yaml
  - servicemonitor.yaml
  - grafanafolder.yaml
  - grafanadashboard.yaml
  - probe.yaml
generators:
  - sopsgenerator.yaml
