apiVersion: v1
kind: ConfigMap
metadata:
  name: longhorn-default-resource
  namespace: longhorn-system
data:
  default-resource.yaml: |
    "backup-target": "s3://longhorn-backups@us-east-2/"
    "backup-target-credential-secret": "minio-backup-secret"
    "backupstore-poll-interval": "180"
---
# Source: longhorn/templates/default-setting.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: longhorn-default-setting
  namespace: longhorn-system
data:
  default-setting.yaml: |-
    default-data-path: "/var/mnt/longhorn"
    priority-class: "longhorn-critical"
    disable-revision-counter: "{\"v1\":\"true\"}"
