namespace: thanos
resources:
  - deployment.yaml
  - service.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - serviceaccount.yaml
  - servicemonitor.yaml
  - grafanadashboard.yaml
  - prometheusrule.yaml
  - telemetry.yaml
