apiVersion: v1
kind: Secret
metadata:
    name: thanos-objectstore
type: Opaque
stringData:
    thanos.yaml: ENC[AES256_GCM,data:E54MkT9v71dVjpzBzF434Lp3wGPHEJSiuYtMdcH0HTQzBIFk4iM5+XOmTqzyMKhKgMC/UowadcN58lYw+SF5lAtwt2zHQ2x3SxCZmMDNcTdSiZlkrAEHnZviK96Ub0bFcpyxzvyo+aasafVbLN2CiYK1f5IWErZauGzflw44h9yK9BWWGEoUmUWC30GiR1Nm8e2iN8fthp4LGD/5yEpTW/43YFzI5LX81aRHoN7vyxePLSZmOxZq,iv:/7NJNjKHz6KP/+74MBRL6xplSFcSn1Shbc0wKUVNGzw=,tag:pFKFHAVDNalNauK2LWq7EQ==,type:str]
sops:
    age:
        - recipient: age15x8mqr8j40rtzeg98wa536jt85276crszk7qcrprndveq4049esq6padka
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTUFUyZlBKRkZ5OUR1SWpp
            dU4xMGdSTENzT05FY05FcTdHRXhKQXdDOGxnCng3STdTRytqejBCNzd1Qml0dFFV
            VVAxWW94NEV2djVIYmN4R1RTZktsQjQKLS0tIFdyK2cvejlKZjFVdms1cWl1RW1v
            Vk94UExXaGNqUU1aU3dZbXpLd0hKcUkKEyEPibSbdcw8n2NfeYAchC5ZZykcoRlL
            6RXIRwEjcCG5HLMtLyQAO/Jh2i6RheKQ6rSDOlsxMMIUhx7omf2H9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-14T22:53:04Z"
    mac: ENC[AES256_GCM,data:jrtrlkHTihhAaXzJWs73jfWR7LRDBqZ4D3pYbhTzG701LoAFfHiVriKfrUDb97BkeqhbCIo5SgrUcJHlfuMTI4PVc0vBT/2GOv3vctPLursF4Sy22LoHuf/ezGX2WjSn+A6HagAC1RLd71TaIOL1+WEwY3Usr1xHjqqrF1lBqTo=,iv:2KxLy91fSbKWi76qBOnSCRWsbdl9LzKpnnukxdnW1p4=,tag:pufos+ec5/sQ/GHT9FDpLA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: thanossidecar-tracing-config
type: Opaque
stringData:
    tracing.yaml: ENC[AES256_GCM,data:v5TfeUuCuFD3QAiK1QEMmDtE6suommErUablrda4pVoUQ4SvgwzZtmVXem36PyM+0pcPbtYzS9DN6YwryNRERZtKoxz3Umqk5QoS+FCR9LHhg2D1MZSF1bsdpBaAAnFzIy2CPElHnr4nnU8xi/+rP0rOpRlTFOZfWAthxlJ6in8x10toEknEBdAz6Sc8C8XYs34MS1Hh5cXYZqy/B9NI2gA7YAAELYrVTbEtYGLCT48juud7VJxq/F4PkevMwm1iBkFDpoTkI8/BwledZwcwUliH+00BLd0fSfDKpu3ECLTmIWNnd52wbYIwtcSF1nNBU9Ih3TxK848qT2lWEmv58DN9hP02ArOPGJxvRLXyP2cmu/gunx3wGQ/ymCcDzYK4YKbubFQg5cQvN+jU29vmQI8qg0jdw14FvlI6QcDACRwXgs7DVb41IXigBPavkg4FZR0dtNkIp3qORQ==,iv:8jPA7+P8EvkQV2PtwHoE+WShbt9y0ZQ8L0BWLKokJ7w=,tag:La5WDjJ7MiYcrBOZNRGFyA==,type:str]
sops:
    age:
        - recipient: age15x8mqr8j40rtzeg98wa536jt85276crszk7qcrprndveq4049esq6padka
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTUFUyZlBKRkZ5OUR1SWpp
            dU4xMGdSTENzT05FY05FcTdHRXhKQXdDOGxnCng3STdTRytqejBCNzd1Qml0dFFV
            VVAxWW94NEV2djVIYmN4R1RTZktsQjQKLS0tIFdyK2cvejlKZjFVdms1cWl1RW1v
            Vk94UExXaGNqUU1aU3dZbXpLd0hKcUkKEyEPibSbdcw8n2NfeYAchC5ZZykcoRlL
            6RXIRwEjcCG5HLMtLyQAO/Jh2i6RheKQ6rSDOlsxMMIUhx7omf2H9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-14T22:53:04Z"
    mac: ENC[AES256_GCM,data:jrtrlkHTihhAaXzJWs73jfWR7LRDBqZ4D3pYbhTzG701LoAFfHiVriKfrUDb97BkeqhbCIo5SgrUcJHlfuMTI4PVc0vBT/2GOv3vctPLursF4Sy22LoHuf/ezGX2WjSn+A6HagAC1RLd71TaIOL1+WEwY3Usr1xHjqqrF1lBqTo=,iv:2KxLy91fSbKWi76qBOnSCRWsbdl9LzKpnnukxdnW1p4=,tag:pufos+ec5/sQ/GHT9FDpLA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
