namespace: docker-registry
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - virtualservice.yaml
  - persistentvolumeclaim.yaml
  - grafanafolder.yaml
  - grafanadashboard.yaml
  - servicemonitor.yaml
  - probe.yaml
