namespace: kanboard
resources:
  - namespace.yaml
  - persistentvolumeclaim.yaml
  - deployment.yaml
  - service.yaml
  - authorizationpolicy.yaml
  - virtualservice.yaml
  - probe.yaml
generators:
  - sopsgenerator.yaml
