apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: grafana-postgres-18
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:17.5

  bootstrap:
    initdb:
      database: grafana
      owner: grafana
      import:
        type: microservice
        databases:
          - grafana
        source:
          externalCluster: nas
        #postImportApplicationSQL:
        #- |
        #  INSERT YOUR SQL QUERIES HERE
  storage:
    size: 5Gi
    storageClass: longhorn-local

  monitoring:
    enablePodMonitor: true

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: minio-store

  externalClusters:
    - name: nas
      connectionParameters:
        # Use the correct IP or host name for the source database
        host: 192.168.123.170
        user: postgres
        dbname: postgres
      password:
        name: nas-psql-postgres-password
        key: password
