apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: grafana-postgres
spec:
  allowCrossNamespaceImport: true
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  datasource:
    name: grafana-postgres
    type: postgres
    isDefault: false
    url: grafana-postgres-18-ro.grafana.svc:5432
    user: $username
    access: proxy
    jsonData:
      database: grafana
      postgresVersion: 1800
      sslmode: disable
      timescaledb: false
    secureJsonData:
      password: $password
  valuesFrom:
    - targetPath: secureJsonData.password
      valueFrom:
        secretKeyRef:
          name: grafana-postgres-18-app
          key: password
    - targetPath: user
      valueFrom:
        secretKeyRef:
          name: grafana-postgres-18-app
          key: username
