apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: grafana-postgres-18
spec:
  schedule: "0 10 1 * * *"
  cluster:
    name: grafana-postgres-18
  backupOwnerReference: self
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
