apiVersion: v1
kind: Secret
metadata:
    name: nas-psql-postgres-password
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:KcG+ofFga1kbu/ben5McAQ==,iv:o9W7xhKw/KzGcIVMmq7r8NRCft5Cvkl5AyqjPveqd6Q=,tag:vB2ke3/HJAQytEEA81QbGw==,type:str]
sops:
    age:
        - recipient: age15x8mqr8j40rtzeg98wa536jt85276crszk7qcrprndveq4049esq6padka
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpeWQ5b21OUUlJVHhFYzhw
            WHJaYjhIVGQrckVhd3V2WVV0eERkVEE3UkRVCnZWM3k3TEk3Qno2T1Z1WUlPQjNX
            SWJNMnY5SnVaUTY3QzNmUGgrK21rbU0KLS0tIG0rNzRBMmd3NTBFTnFybmlyM21M
            MUNwMlJnbzZ1Q3FleHZVVXgzNEZaUkUKUq2HOEtxFSBXFfSQf0YrZ8fbCY2bSbZI
            hbgryiXspr9SK2mnVBbq0Y50kWcBMH8ocdSmw7wVmDR5nq+doo8TSw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-27T02:37:47Z"
    mac: ENC[AES256_GCM,data:7139mjMflCq59xIVUC3c6+ORfEDRsYJH6zrU3DT3/+qt03p3MyYTnSygXNjh9hMsMkaBfXTUDgP45QHzpx/OFs/GKYPv4dYvC25/o+Y25p25d/3DViK4K//TkqTrvvtGna3s5HouQj5/lsZj/kVBaLkbkrfN6Llm9kTzLdl5jlk=,iv:5CPj+7b5edF5hDuTXYMu62Hb+eznmpgj5rPHsXR+nwI=,tag:H2suq3BSszmSerh4m8k7fA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: postgres-backup-creds
type: Opaque
stringData:
    access-id: ENC[AES256_GCM,data:1aE/eqOMfUMaWWfyhxz2l2U=,iv:AsfLyjE9nMVa1Js58uDDACHUSDmztiSsysK+HKfrEjs=,tag:6KfDTuWnPCby9r4PPDgFhw==,type:str]
    secret-key: ENC[AES256_GCM,data:szpGs98DLjkc0kqMF+IJ4FI5fGFlaFkV,iv:j/RmJ8wgBWG8fAX2+6UbNlDth1lyTVyAh9u4tAhv30M=,tag:kHtULsYXUcGaF9mw+e8E2Q==,type:str]
sops:
    age:
        - recipient: age15x8mqr8j40rtzeg98wa536jt85276crszk7qcrprndveq4049esq6padka
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpeWQ5b21OUUlJVHhFYzhw
            WHJaYjhIVGQrckVhd3V2WVV0eERkVEE3UkRVCnZWM3k3TEk3Qno2T1Z1WUlPQjNX
            SWJNMnY5SnVaUTY3QzNmUGgrK21rbU0KLS0tIG0rNzRBMmd3NTBFTnFybmlyM21M
            MUNwMlJnbzZ1Q3FleHZVVXgzNEZaUkUKUq2HOEtxFSBXFfSQf0YrZ8fbCY2bSbZI
            hbgryiXspr9SK2mnVBbq0Y50kWcBMH8ocdSmw7wVmDR5nq+doo8TSw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-27T02:37:47Z"
    mac: ENC[AES256_GCM,data:7139mjMflCq59xIVUC3c6+ORfEDRsYJH6zrU3DT3/+qt03p3MyYTnSygXNjh9hMsMkaBfXTUDgP45QHzpx/OFs/GKYPv4dYvC25/o+Y25p25d/3DViK4K//TkqTrvvtGna3s5HouQj5/lsZj/kVBaLkbkrfN6Llm9kTzLdl5jlk=,iv:5CPj+7b5edF5hDuTXYMu62Hb+eznmpgj5rPHsXR+nwI=,tag:H2suq3BSszmSerh4m8k7fA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
