namespace: miniflux
resources:
  - namespace.yaml
  - postgres
  - deployment.yaml
  - service.yaml
  - virtualservice.yaml
  - authorizationpolicy.yaml
  - probe.yaml

generatorOptions:
 disableNameSuffixHash: true

configMapGenerator:
- name: miniflux-env
  env: config/miniflux.env

generators:
  - sopsgenerator.yaml

