apiVersion: v1
kind: Service
metadata:
  name: miniflux-web
spec:
  selector:
    app.kubernetes.io/name: miniflux
    app.kubernetes.io/component: web
  ports:
    - name: miniflux-http
      port: 80
      targetPort: http
