namespace: nats-io
resources:
  - namespace.yaml
  - service.yaml
  - statefulset.yaml
  - virtualservice.yaml
  - servicemonitor.yaml
  - prometheusrule.yaml
  - grafanafolder.yaml
  - grafanadashboard.yaml
  - probe.yaml
generators:
  - sopsgenerator.yaml
