resources:
- cert-manager-operator
- prometheus-operator
- grafana-operator
- external-secrets-operator
- redis-operator
- opentelemetry-operator
# - minio-operator

patches:
- path: crd-patch.yaml
  target:
    kind: CustomResourceDefinition
