# Source: redis/templates/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: grafana-redis
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: redis
    app.kubernetes.io/version: 0.16.5
    app.kubernetes.io/component: middleware
spec:
  selector:
    matchLabels:
      app: grafana-redis
      redis_setup_type: standalone
      role: standalone
  endpoints:
    - port: redis-exporter
      interval: 30s
      scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
      - grafana
---
# Source: redis/templates/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: grafana-alerting-redis
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: redis
    app.kubernetes.io/version: 0.16.5
    app.kubernetes.io/component: middleware
spec:
  selector:
    matchLabels:
      app: grafana-alerting-redis
      redis_setup_type: standalone
      role: standalone
  endpoints:
    - port: redis-exporter
      interval: 30s
      scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
      - grafana
