namespace: minio
resources:
  - namespace.yaml
  - service.yaml
  - virtualservice.yaml
  - authorizationpolicy.yaml
  - servicemonitor.yaml
  - statefulset.yaml
  - grafanafolder.yaml
  - grafanadashboard.yaml
  # - tenant.yaml
generators:
  - sopsgenerator.yaml
