apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: grafana-postgres-https-30s
spec:
  jobName: grafana-postgres-healthz-https  # Unique job name for Prometheus
  interval: 30s
  scrapeTimeout: 30s
  module: https_skip_verify_30s  # Use the new module you created
  prober:
    url: blackbox-exporter.blackbox-exporter.svc.cluster.local.:19115  # Your Blackbox Exporter service
    scheme: http  # The scheme to connect to the exporter itself
  targets:
    staticConfig:
      static:
        - https://grafana-postgres-healthz.grafana.svc.cluster.local.:8000/healthz
---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: grafana-http-30s
spec:
  jobName: grafana-http-30s
  interval: 30s
  scrapeTimeout: 30s
  module: http_2xx_30s
  prober:
    url: blackbox-exporter.blackbox-exporter.svc.cluster.local.:19115
  targets:
    staticConfig:
      static:
        - http://grafana-service.grafana.svc.cluster.local.:3000/api/health
---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: grafana-tcp-30s
spec:
  jobName: grafana-tcp-30s
  interval: 30s
  scrapeTimeout: 30s
  module: tcp_connect
  prober:
    url: blackbox-exporter.blackbox-exporter.svc.cluster.local.:19115
  targets:
    staticConfig:
      static:
        # Gitea redis
        - grafana-alerting-redis.grafana.svc.cluster.local.:6379
        - grafana-redis.grafana.svc.cluster.local.:6379
