apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: grafana
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 11.2.1
  name: grafana
spec:
  endpoints:
    - interval: 15s
      port: grafana
      relabelings:
        - action: replace
          replacement: homelab-live
          targetLabel: cluster
  selector:
    matchLabels:
      app: grafana
      app.kubernetes.io/managed-by: grafana-operator
