apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo-compactor
  labels:
    helm.sh/chart: tempo-distributed-1.52.9
    app.kubernetes.io/name: tempo
    app.kubernetes.io/instance: tempo
    app.kubernetes.io/component: compactor
    app.kubernetes.io/part-of: memberlist
    app.kubernetes.io/version: "2.9.0"
    app.kubernetes.io/managed-by: Helm
spec:
  # replicas: 2
  replicas: 1
  minReadySeconds: 60
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: tempo
      app.kubernetes.io/instance: tempo
      app.kubernetes.io/component: compactor
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        helm.sh/chart: tempo-distributed-1.52.9
        app.kubernetes.io/name: tempo
        app.kubernetes.io/instance: tempo
        app.kubernetes.io/version: "2.9.0"
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: compactor
        app.kubernetes.io/part-of: memberlist
        app.homelab/environment: prod
        app.homelab/huid: huid-ovz6vtle
        app.homelab/owner: homelab.techservices.data.observability
        app.homelab/service: Tempo
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "3200"
        prometheus.io/scrape: "true"
    spec:
      serviceAccountName: tempo
      securityContext:
        fsGroup: 1000
      enableServiceLinks: false
      
      initContainers:
        []
      containers:
        - args:
            - -target=compactor
            - -config.file=/conf/tempo.yaml
            # - -mem-ballast-size-mbs=1024
            - -mem-ballast-size-mbs=512
          image: docker.io/grafana/tempo:2.9.0
          imagePullPolicy: IfNotPresent
          name: compactor
          ports:
            - containerPort: 3200
              name: http-metrics
            - containerPort: 7956
              name: http-memberlist
          # env:
          #     
          #   - name: GOMEMLIMIT
          #     valueFrom:
          #       resourceFieldRef:
          #         divisor: "0"
          #         resource: requests.memory
          livenessProbe:
            httpGet:
              path: /ready
              port: http-metrics
            initialDelaySeconds: 120
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /ready
              port: http-metrics
            initialDelaySeconds: 90
            timeoutSeconds: 1
          # resources:
          #   limits:
          #     memory: 3584Mi
          #   requests:
          #     cpu: 1.5
          #     memory: 3Gi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
          volumeMounts:
            - mountPath: /conf
              name: config
            - mountPath: /runtime-config
              name: runtime-config
            - mountPath: /var/tempo
              name: tempo-compactor-store
      terminationGracePeriodSeconds: 30
      # affinity:
      #   podAntiAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       - labelSelector:
      #           matchLabels:
      #             app.kubernetes.io/name: tempo
      #             app.kubernetes.io/instance: tempo
      #             app.kubernetes.io/component: compactor
      #         topologyKey: kubernetes.io/hostname
      #     preferredDuringSchedulingIgnoredDuringExecution:
      #       - weight: 100
      #         podAffinityTerm:
      #           labelSelector:
      #             matchLabels:
      #               app.kubernetes.io/name: tempo
      #               app.kubernetes.io/instance: tempo
      #               app.kubernetes.io/component: compactor
      #           topologyKey: topology.kubernetes.io/zone
        
      volumes:
        - name: config
          configMap:
            name: tempo-config
            items:
              - key: "tempo.yaml"
                path: "tempo.yaml"
        - name: runtime-config
          configMap:
            name: tempo-runtime
            items:
              - key: "overrides.yaml"
                path: "overrides.yaml"
        - name: tempo-compactor-store
          emptyDir: {}
