namespace: cnpg-system
resources:
  - https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/refs/heads/main/releases/cnpg-1.27.0.yaml
  # Barman cloud CNPG-I plugin https://cloudnative-pg.io/plugin-barman-cloud/docs/installation/
  # renovate: datasource=github-releases depName=cloudnative-pg/plugin-barman-cloud
  - https://github.com/cloudnative-pg/plugin-barman-cloud/releases/download/v0.7.0/manifest.yaml
  - grafanafolder.yaml
  - grafanadashboard.yaml
  - podmonitor.yaml
  - prometheusrule.yaml
