type: MEMCACHED
config:
  addresses:
    # Use the same DNS discovery address for your Thanos Memcached service
    - thanos-memcached-index.thanos.svc.cluster.local:11211
  # timeout: 500ms
  timeout: 1s
  max_idle_connections: 100
  max_async_concurrency: 20
  max_async_buffer_size: 10000
  # Set max_item_size to 1MB (1048576 bytes) to match the recommended Memcached -I flag
  max_item_size: 1MiB
  max_get_multi_concurrency: 100
  max_get_multi_batch_size: 0
  dns_provider_update_interval: 10s
