namespace: thanos
resources:
  - namespace.yaml
  - compactor
  - query
  - query-frontend
  - receive
  - store
  - ruler
  - grafanafolder.yaml
  - grafanadashboard.yaml
  - probe.yaml

generators:
  - sopsgenerator.yaml
