apiVersion: v1
data:
  config.yml: |-
    "modules":
      "http_2xx_60s":
        "timeout": "60s"
        "http":
          "preferred_ip_protocol": "ip4"
        "prober": "http"
      "http_2xx_30s":
        "timeout": "30s"
        "http":
          "preferred_ip_protocol": "ip4"
        "prober": "http"
      "https_skip_verify_30s":
        "prober": "http"
        "timeout": "30s"
        "http":
          "preferred_ip_protocol": "ip4"
          "tls_config":
            "insecure_skip_verify": true
      "http_post_2xx":
        "http":
          "method": "POST"
          "preferred_ip_protocol": "ip4"
        "prober": "http"
      "irc_banner":
        "prober": "tcp"
        "tcp":
          "preferred_ip_protocol": "ip4"
          "query_response":
          - "send": "NICK prober"
          - "send": "USER prober prober prober :prober"
          - "expect": "PING :([^ ]+)"
            "send": "PONG ${1}"
          - "expect": "^:[^ ]+ 001"
      "pop3s_banner":
        "prober": "tcp"
        "tcp":
          "preferred_ip_protocol": "ip4"
          "query_response":
          - "expect": "^+OK"
          "tls": true
          "tls_config":
            "insecure_skip_verify": false
      "ssh_banner":
        "prober": "tcp"
        "timeout": "30s"
        "tcp":
          "preferred_ip_protocol": "ip4"
          "query_response":
          - "expect": "^SSH-2.0-"
      "tcp_connect":
        "prober": "tcp"
        "tcp":
          "preferred_ip_protocol": "ip4"
      dns_udp:
        prober: dns
        timeout: 5s
        dns:
          query_name: "www.prometheus.io"
          query_type: "A"
          valid_rcodes:
            - NOERROR
          validate_answer_rrs:
            fail_if_matches_regexp:
              - ".*127.0.0.1"
            fail_if_all_match_regexp:
              - ".*127.0.0.1"
            fail_if_not_matches_regexp:
              - "www.prometheus.io.\t300\tIN\tA\t127.0.0.1"
            fail_if_none_matches_regexp:
              - "127.0.0.1"
          validate_authority_rrs:
            fail_if_matches_regexp:
              - ".*127.0.0.1"
          validate_additional_rrs:
            fail_if_matches_regexp:
              - ".*127.0.0.1"
      dns_soa:
        prober: dns
        dns:
          query_name: "prometheus.io"
          query_type: "SOA"
      dns_tcp_example:
        prober: dns
        dns:
          transport_protocol: "tcp" # defaults to "udp"
          preferred_ip_protocol: "ip4" # defaults to "ip6"
          query_name: "www.prometheus.io"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: blackbox-exporter
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 0.25.0
  name: blackbox-exporter-configuration
