namespace: blackbox-exporter
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - deployment.yaml
  - service.yaml
  - networkpolicy.yaml
  - servicemonitor.yaml
  - grafanafolder.yaml
  - grafanadashboard.yaml
  - prometheusrule.yaml
  - telemetry.yaml
generators:
  - sopsgenerator.yaml
configMapGenerator:
- files:
  - files/config.yml
  name: blackbox-exporter-configuration
  options:
    immutable: true
